# Generated by Django 5.1.6 on 2025-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_qrcodeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
